FROM node:20

EXPOSE 8000

# install pnpm
ENV SHELL /bin/bash
RUN curl -fsSL https://get.pnpm.io/install.sh | env PNPM_VERSION=8.6.12 sh -
ENV PATH="/root/.local/share/pnpm:$PATH"

# build common lib
# WORKDIR /common
# RUN pnpm install
# RUN pnpm run build

# setup backend app
WORKDIR /app
# RUN pnpm install --frozen-lockfile


ENTRYPOINT ["/bin/sh","./launch-dev.sh"]
