FROM node:20

EXPOSE 8000

ENV SHELL /bin/bash
RUN curl -fsSL https://get.pnpm.io/install.sh | env PNPM_VERSION=8.6.12 sh -
ENV PATH="/root/.local/share/pnpm:$PATH"

WORKDIR /app

ENTRYPOINT ["/bin/sh","./launch-dev.sh"]
